{
    name:'BARROCO 新款钟表节拍器',
    picSrc:'img/flash/1.jpg',
    fprice:'188',
    price:'210.00',
    rest:49
}
{
    name:'罗德24首随想曲',
    picSrc:'img/flash/2.jpg',
    fprice:'8',
    price:'14.00',
    rest:11
}
{
    name:'视唱基础教程',
    picSrc:'img/flash/3.jpg',
    fprice:'5',
    price:'24.00',
    rest:31
}
{
    name:'现代钢琴教程(3)',
    picSrc:'img/flash/4.jpg',
    fprice:'5',
    price:'15.00',
    rest:50
}
{
    name:'小提琴综合教程第6册',
    picSrc:'img/flash/5.jpg',
    fprice:'5',
    price:'22.70',
    rest:50
}
{
    name:'一个星期学会吉他弹唱',
    picSrc:'img/flash/6.jpg',
    fprice:'5',
    price:'25.80',
    rest:30
}
{
    name:'音阶与琶音',
    picSrc:'img/flash/7.jpg',
    fprice:'5',
    price:'18.00',
    rest:30
}
{
    name:'中外通俗钢琴曲集',
    picSrc:'img/flash/8.jpg',
    fprice:'8',
    price:'28.10',
    rest:49
}
{
    name:'拜厄钢琴基本教程上册',
    picSrc:'img/flash/9.jpg',
    fprice:'9.9',
    price:'30.00',
    rest:10
}